Create Database HeyURLDB;

CREATE TABLE URLS(
IDURL INT NOT NULL PRIMARY KEY IDENTITY (1,1),
SHORTURL VARCHAR (5) NOT NULL UNIQUE,
ORIGINALURL VARCHAR (128),
COUNTACCESS INT,
URLDATE DATETIME
)

CREATE TABLE LOGURL(
IDLOG INT NOT NULL PRIMARY KEY IDENTITY (1,1),
IDURL INT NOT NULL FOREIGN KEY REFERENCES URLS(IDURL),
USERPLATFORM VARCHAR (25),
BROWSER VARCHAR (25),
LOGDATE DATETIME 
)


select * from URLS